name: Build and Release binaries

on:
  push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Poetry Pyinstaller plugin
        run: |
          poetry self add poetry-pyinstaller-plugin

      - name: Install dependencies
        run: poetry install

      - name: Build project
        run: poetry build

      - name: Create release directory
        run: mkdir -p dist/pyinstaller/linux/

      - name: Move build artifacts
        run: mv dist/pyinstaller/*/ptpt dist/pyinstaller/linux/ptpt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-ptpt
          path: dist/pyinstaller/linux/ptpt


  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Poetry Pyinstaller plugin
        run: |
          poetry self add poetry-pyinstaller-plugin

      - name: Install dependencies
        run: poetry install

      - name: Build project
        run: poetry build

      - name: Create release directory
        run: mkdir -p dist/pyinstaller/macos/

      - name: Move build artifacts
        run: mv dist/pyinstaller/*/ptpt dist/pyinstaller/macos/ptpt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-ptpt
          path: dist/pyinstaller/macos/ptpt


  create-release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-ptpt
          path: linux-ptpt

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-ptpt
          path: macos-ptpt

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            macos-ptpt
            linux-ptpt
